<div class="top-ftr">
            <ul>
                <li><a href="content.php?cid=<?php echo base64_encode(4); ?>"> Privacy Policy</a></li>
                <li><a href="content.php?cid=<?php echo base64_encode(3); ?>">Terms &amp conditions</a></li>
                <li><a href="">Advertise</a></li>
             
            </ul>
        </div>
        <!-- top footer ends -->
        <!-- bottom footer -->
        <div class="btm-ftr">
            <p><a href="https://www.livenewage.com/" target="_blank"> &copy;All rights are reserved to <b>New Age News</b> </a> &nbsp; &nbsp; &nbsp;  Powered by <a href="https://www.penoft.com" target="_blank"><b>Penoft</b></a></p>
        </div>
