 									<div class="select">
                                    <select id="sortBy" onchange="goto(sortBy.value)">
									  <option value="index">Sort by</option>
									  <option value="starred">Starred</option>
                                        <option value="index">Refresh</option>
                                        <option value="name_asc" onClick="">Name by ascending</option>
										<option value="name_desc">Name by descending</option>
                                        <option value="sector">Sector</option>
                                        <option value="date_asc">Date by ascending</option>
										<option value="date_desc">Date by descending</option>
                                    </select>
                                </div>